version: '3.7'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.16.2-alpine #https://hub.docker.com/r/portainer/portainer-ce/tags
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
