version: '3.7'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.16.2-alpine #https://hub.docker.com/r/portainer/portainer-ce/tags
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  
  registry:
    restart: always
    image: registry:2.8.1
    ports:
      - 5000:5000
    volumes:
      - ./registry/data:/var/lib/registry
  jenkins:
      image: jenkins/jenkins:2.388-jdk11
      privileged: true
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      container_name: jenkins
      volumes:
        - ./jenkins/data:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/local/bin/docker